name: Schedule Tweet

on:
    # schedule:
    push:
        
        # - cron: "*/5 * * * *"  # Run Job every one minute

jobs:
    tweet:
        runs-on: unbuntu-latest
        steps:
            -   name: Checkout 
                uses: actions/checkout@v4
            -   name: Install python Packages
                run: pip install -r requirements.txt

