name: Schedule Tweet

on:
    schedule:
        - cron: "1 * * * *"  # Run Job every one minute

jobs:
    tweet:
        runs-on: unbuntu-latest
        steps:
            - name: Install python Packages
              run: pip install -r requirements.txt

